# Generated by Django 3.0 on 2020-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
