# Generated by Django 3.0.2 on 2020-01-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=30)),
            ],
        ),
    ]
