# Generated by Django 3.0.2 on 2020-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_drop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=30)),
            ],
        ),
    ]
